### ISSUE TITLE
readOAIRecords.py produces xml-files without a closing "</collection>"-tag

### ISSUE THREAD

**Issue by ToVie** [swissbib/contentCollector#3]
readOAIRecords.py writes 'function' object has no attribute 'getRoottag' instead of '</collection>'

The end of a file looks like this:

```
</marc:collection></metadata>
</record>
'function' object has no attribute 'getRoottag'
```

**Comment by oschihin** [comment]
@guenterh : ist der noch offen?

**Comment by guenterh** [comment]
@oschihin 
Wenn ich mir die Fehlermeldung ansehe, vermute ich einen Konfigurationsfehler. 

Es braucht den tag <roottag>

Bitte mitteilen, wenn der Fehler nochmals auftritt

Günter

**Comment by guenterh** [comment]
see
https://github.com/swissbib/contentCollector/commit/2778de10b302d3eab6111eb396183f03fc4818e7
